
export const INTEGRANTES_COMERCIALES = [
  { name: "ESCORCIA CANCHILA JAIRO ANTONIO", email: "jescorcia@equitel.com.co" },
  { name: "OMANA PAREJA SANDRA MILENA", email: "somana@equitel.com.co" },
  { name: "CASTANEDA BARRIENTOS MARIA FERNANDA", email: "mcastaneda@equitel.com.co" },
  { name: "ALCARAZ URREGO CLARA INES", email: "claralcaraz1966@gmail.com" },
  { name: "ZAPATA GAVIRIA LUZ MARINA", email: "lmzapata@equitel.com.co" },
  { name: "ROJAS RUIZ YELENA PAOLA", email: "yrojas@equitel.com.co" },
  { name: "SANCHEZ CRUZ MATEO", email: "masanchez@equitel.com.co" },
  { name: "PATRON MONTES AMAURY RAFAEL", email: "bodegabq@equitel.com.co" },
  { name: "ALCAZAR REYNALES ANDRES JOAQUIN", email: "aalcazar@equitel.com.co" },
  { name: "PANTOJA ACOSTA CESAR AUGUSTO", email: "cpantoja@equitel.com.co" },
  { name: "CARVAJAL CASTRILLON OMAR ANDRES", email: "ocarvajal@equitel.com.co" },
  { name: "OBANDO GAMBOA DAMIAN CLAUDIO", email: "dobando@equitel.com.co" },
  { name: "MANGA FONTALVO GUSTAVO ENRIQUE", email: "gmanga@equitel.com.co" },
  { name: "FLOREZ SAAVEDRA CARLOS EDUARDO", email: "cflorez@equitel.com.co" },
  { name: "LEAL FONSECA JOHN FREDDY", email: "jleal@equitel.com.co" },
  { name: "BARRERA CEPEDA SERGIO DAVID", email: "sbarrera@equitel.com.co" },
  { name: "MONROY RUEDA YESID", email: "ymonroy@equitel.com.co" },
  { name: "DUCUARA SANCHEZ DANIEL FERNANDO", email: "dducuara@equitel.com.co" },
  { name: "FETECUA BERMUDEZ ADRIAN FELIPE", email: "afetecua@equitel.com.co" },
  { name: "ORTIZ RIVEROS STEPHANIE", email: "compras1@equitel.com.co" },
  { name: "ROMERO VASQUEZ CESAR HERNANDO", email: "cromero@equitel.com.co" },
  { name: "GUZMAN MIRA JORGE EDUARDO", email: "jguzman@equitel.com.co" },
  { name: "ECHEVERRI RUBIANO JORGE IVAN", email: "jecheverri@equitel.com.co" },
  { name: "MONTOYA RESTREPO JUAN PABLO", email: "jmontoya@equitel.com.co" },
  { name: "MOSQUERA DAZA JUAN CAMILO", email: "jmosquera@equitel.com.co" },
  { name: "OCHOA REYES ERIKA", email: "cumandescali@equitel.com.co" },
  { name: "BUSTAMANTE AMARILES KATHERINE", email: "kbustamante@equitel.com.co" },
  { name: "ECHEVERRI CARVAJAL EDISON", email: "eecheverri@equitel.com.co" },
  { name: "GIRALDO ZAPATA ARNOBER", email: "agiraldo@equitel.com.co" },
  { name: "GONZALEZ SANDOVAL PAOLA ANDREA", email: "pgonzalez@equitel.com.co" },
  { name: "MORALES HENAO ANDRES FELIPE", email: "amorales@equitel.com.co" },
  // Fixed typo: changed 'hex' to 'email' to match CommercialMember interface
  { name: "SANMARTIN PEREZ HECTOR DAVID", email: "hsanmartin@equitel.com.co" },
  { name: "ATEHORTUA MONTOYA PABLO ARTURO", email: "patehortua@equitel.com.co" },
  { name: "BETANCUR OSPINA MATEO", email: "mbetancur@equitel.com.co" },
  { name: "GIRALDO SANCHEZ MAIRA ALEJANDRA", email: "mgiraldo@equitel.com.co" },
  { name: "GUERRA CASTRILLON MAURICIO", email: "mguerra@equitel.com.co" },
  { name: "HERNANDEZ OSORIO DANNY ALBERTO", email: "dhernandez@equitel.com.co" },
  { name: "PATERNINA GRACIANO JORGE LUIS", email: "jpaternina@equitel.com.co" },
  { name: "PEREZ MUNOZ DANIEL STIVEN", email: "dperez@equitel.com.co" },
  { name: "PINEDA GOMEZ JOSE DARIO", email: "jdpineda@equitel.com.co" },
  { name: "YEPES ALVAREZ MABEL CRISTINA", email: "myepes@equitel.com.co" },
  { name: "ESTRADA DE MOYA LUIS FERNANDO", email: "lestrada@equitel.com.co" },
  { name: "BUSTAMANTE PENAGOS JOHNATAN", email: "jbustamante@equitel.com.co" },
  { name: "URIBE VANEGAS JAIME EDIR", email: "juribe@equitel.com.co" },
  { name: "CAMPOS DEYVER JOHN", email: "jcampos@equitel.com.co" }
];

export const THRESHOLDS = {
  Z_ALTMAN_SAFE: 2.99,
  Z_ALTMAN_DANGER: 1.81,
  RAZON_CORRIENTE_MIN: 1.0,
  ENDEUDAMIENTO_GLOBAL_MAX: 70
};